
author: Guillaume Compagnon
email: gcompagnon@hotmail.com

layout: post
title: Asset and Assets
description: > 
  Personal Blog and bookmarks about 
  Software | Computing | Project | Software | Engineer | Architecture | Innovation | Systems Integration | 
  Continuous Integration | Continuous Deployment | Continuous Delivery | Agile | Devops |
  C++ | C# | Java | Python | MultiThreading | Design Pattern | Commmando | Rapid Application Development |
  Regulatory Reporting | Transaction Reporting | RTS25 | MIFID2 | MIFID II | MIF2 | Solvency 2 | Sol2 | Basel III | US GAAP | IFRS
  Stock | Equity | Fixed Income | Asset Management | Swap | Interest Rate | Forex | Trading | Pricing | 
  PTP | NTP | Clock Synchronization | Low Latency | GPS |
  Derivative | Option | Future | American style Option | European style Option | 
  Market Data | Benchmark | Index | Indexes Asset Reallocation | Rebalancing | Drill Drown | Financial engineer |
  Risk Management | Delta | Alpha | Beta | Greeks| Tracking Error | VaR | Value at Risk | FRTB | expected shortfall | Stress Testing |
  Performance | Attribution | Allocation | Selection | Stock Picking | Total return | Scoring |
  CFA | AMF | ECB | Global Association of Risk Professionals | GARP | 

twitter_username: gcompagnon
github_username: gcompagnon
linkedin_username: gcoompagnon

google_analytics: UA-119758867-1

show_downloads: true
rss: rss

theme: minima

gems:
- jekyll-mentions
plugins:
- jekyll-feed
- jekyll-seo-tag
